page_spacing_x: 40
page_spacing_y: 40
page_margin_x: 50
page_margin_y: 50

font_folder: fonts # folder in project
# font_folder: C:\Windows\Fonts # Windows
# font_folder: /usr/share/fonts # Ubuntu
card_height: 1008
card_width: 640
 
card:
  border_size: 2
  border_color: black
  text_defaults:
    font: default.otf
    min_font_size: 10
    max_font_size: 100
    text_color: black
